### ISSUE TITLE
[SUGGESTION] - Mis-Spelling in readme.md

### ISSUE THREAD

**Issue by thuemmeryf** [PokeMiners/website#1]
The Readme.md has a mis-spelling in the last-sentence.  One too many h in Thanks.  Yeah I know its kinda silly but thought you may want to know.

Screen grab:

![image](https://user-images.githubusercontent.com/50596563/120382663-ea600400-c2f1-11eb-83f3-d6aa8538249a.png)

**Comment by marty0678** [comment]
Fixed in a90a557da9c280c807f935f8008f6189a17777b6. Thank you!
