### ISSUE TITLE
[SUGGESTION] - Reports RSS Feed

### ISSUE THREAD

**Issue by Fleker** [PokeMiners/website#2]
**Describe your idea/feedback**
Generate an [RSS feed](https://en.wikipedia.org/wiki/RSS) [with each post](https://pokeminers.com/reports/) to let readers subscribe and receive info when there is a new report. Even something as simple as a headline and link to content would allow readers to regularly visit your site when there is something new.

**What part of the website is this part of?**
This would pertain to the reports primarily

**Comment by marty0678** [comment]
All our posts are also posted to our Discord server in channels you can follow in your own server too if you'd like (not quite the same but something for now at least). Thank you for the suggestion, we'll discuss it!

**Comment by marty0678** [comment]
I forgot to close this, but we do have RSS fields now!

Graphics: https://pokeminers.com/graphics/rss/
Reports: https://pokeminers.com/reports/rss/
