### ISSUE TITLE
raid leaderboard

### ISSUE THREAD

**Issue by fuer-lo** [PokeMiners/website#4]
The individual leaderboards that currently exist.

You have already found this thing and is nothing new in itself, but I just can't find it here, maybe I'm blind, can you help me. however, if it is not here, please add it.

https://twitter.com/poke_miners/status/1403333801015656450/photo/1

- mfg fuer-lo

**Comment by marty0678** [comment]
You can find them here: https://github.com/PokeMiners/pogo_assets/tree/master/Images/Raid%20Stadium

**Comment by fuer-lo** [comment]
Thank you first for the answer I don't know why I didn't find that but I still have one more question, please, can the files be replaced so that they have the same size? Or at least this https://github.com/PokeMiners/pogo_assets/blob/master/Images/Raid%20Stadium/raid_leaderboard_customize_avatar_fx.png

**Comment by fuer-lo** [comment]
Thank you first for the answer I don't know why I didn't find that but I still have one more question, please, can the files be replaced so that they have the same size?
P.S. I thank you for what you are doing and I wish you a good slip.
mfg fuer-lo

**Comment by lewymd** [comment]
We don't resize anything in the repo, all files are presented exactly as they are in the game. If you want to resize them you'll have to do that yourself

**Comment by fuer-lo** [comment]
OK, and just so that it doesn't end up in the wrong neck, there shouldn't be any invitation or prompt.
